= Lifecycle Tools Project Charter
Lifecycle Tools PMC
{version}

== Overview

This charter was developed in accordance with the link:https://www.eclipse.org/projects/dev_process/development_process.php[Eclipse Development Process] and outlines the mission, scope, organization, and development process for the *Lifecycle Tools Project*. This document extends the link:https://www.eclipse.org/projects/dev_process/Eclipse_Standard_TopLevel_Charter_v1.2.php[Eclipse Standard Top-Level Charter v1.2], and includes the required content and overrides which follow. It is anticipated that as the standard charter is updated, this charter will incorporate the changes and make adjustments as seen fit by the PMC, and with approval from the EMO and board of directors.

* Descriptive name: *Lifecycle Tools*
* Nickname: *Lifecycle*


== Mission

The mission of the Lifecycle Tools project is to provide a home and collaboration environment for:

. Open source  tools and technology for managing the application lifecycle (eg., Source Code Management, Continuous Integration, Build Technology)
. Reference implementations of ALM standards and protocols used in ALM systems
. Integrations of exising ALM tools with the Eclipse IDE

This document describes the composition and organization of the project, roles and responsibilities of the participants, and development process for the project.


== Scope

The Lifecycle Tools Top-Level Project is a home for Eclipse projects focusing on the needs of application lifecycle management. The range of projects include tools for accessing task, build information and source code from within the Eclipse IDE as well as non Eclipse specific tools for addressing topics such as build and deployment automation, release engineering, source code management and application documentation.


== Licensing

Projects under the Lifecycle Tools Top-Level Project are permitted to use one of the following two options:

* Eclipse Public License v1.0
* Eclipse Public License v1.0 and Eclipse Distribution License v1.0


== Project Management Committee Participation

The Projects under this Charter are managed by a group known as the Project Management Committee (the “PMC”). Each project must provide a representative to join the Lifecycle Tools PMC. Representatives shall participate in all regular PMC activities.

