= Lifecycle Tools Project Charter


== Overview

This charter was developed in accordance with the link:https://www.eclipse.org/projects/dev_process/development_process.php[Eclipse Development Process] and outlines the mission, scope, organization, and development process for the *Lifecycle Tools Project*. This document extends the link:https://www.eclipse.org/projects/dev_process/Eclipse_Standard_TopLevel_Charter_v1.2.php[Eclipse Standard Top-Level Charter v1.2], and includes the required content and overrides which follow. It is anticipated that as the standard charter is updated, this charter will incorporate the changes and make adjustments as seen fit by the PMC, and with approval from the EMO and board of directors.

* Descriptive name: *Lifecycle Tools*
* Nickname: *Lifecycle*


== Mission

The mission of the Lifecycle Tools project is to provide a home and collaboration environment for:

. Frameworks, APIs and tools for Eclipse-based task and Application Lifecycle Management (ALM)
. Frameworks, APIs and tools for Eclipse-based Source Code Management integrations (SCM)
. Exemplary tools for [http://en.wikipedia.org/wiki/Task-focused_interface task-focused programming] within the Eclipse IDE.
. Reference implementations for open source ALM tools used by the Eclipse community and for open ALM standards such as [http://open-services.net OSLC]

This document describes the composition and organization of the project, roles and responsibilities of the participants, and development process for the project.


== Scope

The Lifecycle Tools Top-Level Project is a home for Eclipse projects focusing on the needs of application lifecycle management. The range of projects include tools for accessing task, build information and source code from within the Eclipse IDE as well as non Eclipse specific tools for addressing topics such as build and deployment automation, release engineering and application documentation.

* A task management tool for developers
* The revolutionary task-focused interface
* A broad ecosystem of Agile and ALM integrations


== Project Management Committee Participation

Each project


== Licensing

Projects under the Lifecycle Tools Top-Level Project are permitted to use one of the following two options:

* Eclipse Public License v1.0
* Eclipse Public License v1.0 and Eclipse Distribution License v1.0


